# Generated by Django 5.0.3 on 2024-04-18 22:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_category_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='dni',
        ),
        migrations.AddField(
            model_name='client',
            name='curp',
            field=models.CharField(default=django.utils.timezone.now, max_length=10, unique=True, verbose_name='Curp'),
            preserve_default=False,
        ),
    ]
