# Generated by Django 3.2.12 on 2024-04-28 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0007_alter_client_curp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='curp',
            field=models.CharField(max_length=18, unique=True, verbose_name='Curp'),
        ),
    ]
